version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/groups/dps"
    schedule:
      interval: "weekly"
    reviewers:
      - "companieshouse/platform-admin"
    registries:
      - github-dependabot
    groups:
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
registries:
  github-dependabot:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.DEPENDABOT_GITHUB_ACCESS_TOKEN}}
