---

- name: Provision Ansible controller with SSH key for remote
  hosts: localhost
  roles:
    - role: companieshouse.general.ssh_key
      vars:
        ssh_key_name: ansible_remote
        ssh_key_vault_path: "{{ vault_base_path }}/aws"

- name: Provision Informix dbspaces and chunks
  hosts: amazon.aws.aws_ec2
  serial: 1
  remote_user: centos
  become: true
  roles:
    - role: informix-db
      vars:
        informix_db_logs_path: "{{ informix_logs_path }}"
        informix_db_server_name_suffix: "{{ informix_server_name_suffix }}"
        informix_db_vault_path: "{{ vault_base_path }}/informix"
