---

# Provision Ansible controller with SSH key for remote
- hosts: localhost
  roles:
    - role: ssh-key
      vars:
        ssh_key_name: ansible_remote
        hashicorp_vault_private_key_path: "{{ vault_base_path }}/aws"

# Provision Informix dbspaces and chunks
- hosts: aws_ec2
  serial: 1
  remote_user: centos
  become: yes
  roles:
    - role: informix-db
      vars:
        informix_db_vault_path: "{{ vault_base_path }}/informix"
