---

- name: Provision Ansible controller with SSH key for remote
  hosts: localhost
  roles:
    - role: companieshouse.general.ssh_key
      vars:
        ssh_key_name: ansible_remote
        ssh_key_vault_path: "{{ vault_base_path }}/aws"

- name: Provision iSCSI devices
  hosts: amazon.aws.aws_ec2
  serial: 1
  remote_user: centos
  become: true
  roles:
    - role: iscsi-devices
      vars:
        iscsi_devices_vault_path: "{{ vault_base_path }}/iscsi"
