---

- name: Provision Ansible controller with SSH key for remote
  hosts: localhost
  roles:
    - role: companieshouse.general.ssh_key
      vars:
        ssh_key_name: ansible_remote
        ssh_key_vault_path: "{{ vault_base_path }}/aws"

- name: Provision Informix management scripts and cron jobs
  hosts: aws_ec2
  serial: 1
  remote_user: centos
  become: true
  roles:
    - role: informix-management
      vars:
        informix_management_alerts_enabled: true
        informix_management_alerts_vault_path: "{{ vault_base_path }}/alerts"
