---

roles:
  - src: https://github.com/companieshouse/ansible-role-informix-db
    name: informix-db
    version: "1.0.6"
  - src: https://github.com/companieshouse/ansible-role-informix-management
    name: informix-management
    version: "1.0.6"
  - src: https://github.com/companieshouse/ansible-role-iscsi-devices
    name: iscsi-devices
    version: "1.1.3"

collections:
  - name: amazon.aws
    version: "8.1.0"
  - name: community.general
    version: "9.3.0"
  - name: companieshouse.general
    version: "1.1.0"
