plugin: aws_ec2
boto_profile: heritage-live-eu-west-2

regions:
  - eu-west-2

filters:
  tag:Environment: live
  tag:ServiceSubType: dps

keyed_groups:
  - key: tags
    prefix: tag
    separator: "_"

hostnames: private-ip-address
