---

- name: Set EC2 metadata facts
  amazon.aws.ec2_metadata_facts:

- name: Set host facts for passwd database
  getent:
    database: passwd

- name: Check required variables are set
  assert:
    that:
      - environment_name is defined and environment_name | trim | length > 0
    msg: "Required variable(s) empty or undefined"

- name: Set CloudWatch agent facts for config population
  set_fact:
    cloudwatch_agent: "{{ cloudwatch_agent_defaults | combine(cloudwatch_agent_overrides | default({})) }}"
    cloudwatch_log_stream_name: "{{ ansible_ec2_instance_id }}_{{ ansible_ec2_hostname }}"
    region: "{{ ansible_ec2_instance_identity_document_region }}"

- name: Create CloudWatch agent primary configuration file
  template:
    src: templates/cloudwatch-config.json.j2
    dest: "{{ cloudwatch_agent.config_dir }}/cloudwatch-config.json"
    trim_blocks: false

- name: Start CloudWatch agent using primary configuration file
  command:
    cmd: "{{ cloudwatch_agent.path }} -a fetch-config -m ec2 -s -c file:{{ cloudwatch_agent.config_dir }}/cloudwatch-config.json"

- name: Create shared log rotation configuration for DPS services
  template:
    src: templates/logrotate.dps.conf.j2
    dest: "{{ dps_log_rotation_config_path }}"

- import_tasks: cron.yml

- name: Allow logrotate to modify CloudWatch log
  community.general.sefcontext:
    target: "{{ item }}"
    setype: var_log_t
    state: present
  loop:
    - /opt/aws/amazon-cloudwatch-agent/logs
    - /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log
  register: selinux_context

- name: Apply SELinux file context for CloudWatch log
  command: "restorecon {{ item }}"
  loop:
    - /opt/aws/amazon-cloudwatch-agent/logs
    - /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log
  when: selinux_context.changed

- import_tasks: tools.yml

- name: Add host entry for SQL client connectivity
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1   {{ ansible_facts.hostname }}"

- name: Find application-specific CloudWatch configuration files
  find:
    paths: "{{ cloudwatch_agent.config_dir }}"
    patterns: 'cloudwatch-config-*.json'
  register: cloudwatch_configs

- name: Add configuration for DPS services to CloudWatch agent
  command:
    cmd: "{{ cloudwatch_agent.path }} -a append-config -m ec2 -s -c file:{{ item.path }}"
  loop: "{{ cloudwatch_configs.files }}"
